force-app/main/default/objects/Contact/fields/ContactType__c.field-meta.xml
<CustomField>
    <fullName>ContactType__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Field Worker</fullName>
            </value>
            <value>
                <fullName>Survey Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LoginEmail__c.field-meta.xml
<CustomField>
    <fullName>LoginEmail__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address of auth0 user (field worker) for grassroots mobile survey app.</description>
    <inlineHelpText>Email address of auth0 user (field worker) for grassroots mobile survey app.</inlineHelpText>
    <label>Login Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FieldWorkerClientRelation__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.ContactType__c</field>
            <operation>equals</operation>
            <value>Survey Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Field Worker Relationships</relationshipLabel>
    <relationshipName>FieldWorkerRelationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieldWorkerClientRelation__c/fields/FieldWorker__c.field-meta.xml
<CustomField>
    <fullName>FieldWorker__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Field Worker</label>
    <lookupFilter>
      <active>true</active>
      <filterItems>
          <field>Contact.ContactType__c</field>
          <operation>equals</operation>
          <value>Field Worker</value>
      </filterItems>
      <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Relationships</relationshipLabel>
    <relationshipName>ClientRelationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

test/main/default/classes/ContactValidationRuleTest.cls
@isTest
public with sharing class ContactValidationRuleTest {
  @isTest
  public static void testUserClientRelation() {
    Contact c = new Contact(
      LastName = 'Test1',
      LoginEmail__c = 'test1@example.com',
      ContactType__c = 'Survey Client');
    insert c;
    Contact u = new Contact(
      LastName = 'Test2',
      LoginEmail__c = 'test2@example.com',
      ContactType__c = 'Field Worker');
    insert u;
    insert new FieldWorkerClientRelation__c(
      Client__c = c.Id,
      FieldWorker__c = u.Id
    );  
    System.assert([SELECT COUNT() FROM FieldWorkerClientRelation__c] > 0, 'relationship record is not created.');
  }

    @isTest
    public static void testSurveyUserFieldRestriction() {
      Contact c = new Contact(
        LastName = 'Test',
        LoginEmail__c = 'test@example.com',
        ContactType__c = 'Survey Client');
      insert c;
      String message;
      try {
        insert new FieldWorkerClientRelation__c(
          Client__c = c.Id,
          FieldWorker__c = c.Id
        );
      } catch (Exception e) {
        message = e.getMessage();
      }
      System.assert(!String.isBlank(message), 'validation rule for field worker filed is not working');
      System.assert(message.contains('You must specify &quot;Field Worker&quot; type contact for the Field Worker field.'), 'message of validation rule for field worker filed is wrong');
    }

    @isTest
    public static void testSurveyClientFieldRestriction() {
      Contact c = new Contact(
        LastName = 'Test',
        LoginEmail__c = 'test@example.com',
        ContactType__c = 'Field Worker');
      insert c;
      String message;
      try {
        insert new FieldWorkerClientRelation__c(
          Client__c = c.Id,
          FieldWorker__c = c.Id
        );
      } catch (Exception e) {
        message = e.getMessage();
      }
      System.assert(!String.isBlank(message), 'validation rule for survey client filed is not working');
      System.assert(message.contains('You must specify &quot;Survey Client&quot; type contact for the Survey Client field.'), 'message of validation rule for survey client filed is wrong');
    }
}